image: silkeh/clang:8

before_script:
  - export LD_LIBRARY_PATH=${PWD}/build/:${LD_LIBRARY_PATH}
  - sudo apt install libtbb-dev

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release
    - make -j

# run tests using the binary built before
test:
  stage: test
  script:
    - cd build/tests
    - ./test_internal_functions -s
