os: linux
language: cpp
dist: bionic
compiler: clang
before_script:
  - export BUILD_DIR=${PWD}/build
  - sudo apt-get update
  - sudo apt-get -y install libtbb-dev libc++-dev
script:
    # Build
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release
    - make -j 4
    # Tests
    - cd ${BUILD_DIR}/tests
    - ./test_internal_functions
    - ./test_locks
    - ./test_barriers
